### PR TITLE
fix: hidden_domain now detects at every auth step

### LINKED ISSUE #206: `reject-*` at the end of auth-chain prevents `hidden_domain` usage
Hello!

I've been experimenting with `reject-static` and noticed that adding it to the else segment of basicauth breaks the `hidden_domain` behavior.

The issue lies in the initial condition within `requireBasicAuth`, which immediately passes validation to the next provider in the chain, effectively skipping the `hidden_domain` check.

https://github.com/SenseUnit/dumbproxy/blob/dbdbd4a257313f05f00336192f2822d798c573d7/auth/common.go#L24-L27

Since none of the `reject-*` handlers process `hidden_domain` inside their own `Validate` methods, the check never actually happens.

I'm not very proficient in Go, but I'd like to propose a more robust approach: we should validate `hidden_domain` within `requireBasicAuth` immediately, before falling back to `next.Validate()`. I'll submit a PR with these changes.

This fix should resolve the issue with `reject-*` at the end of the chain and ensure that every `hidden_domain` is checked at each stage of the basicauth sequence, rather than only the final one.

### PR DESCRIPTION
**Pull request by sanekb**
close #206

### CODE REVIEW

File: auth/common.go [hunk 1]
```diff
@@ -22,19 +22,28 @@ func matchHiddenDomain(host, hidden_domain string) bool {
...
-		!matchHiddenDomain(req.URL.Host, hidden_domain) &&
-		!matchHiddenDomain(req.Host, hidden_domain) {
-		http.Error(wr, BAD_REQ_MSG, http.StatusBadRequest)
-	} else {
-		wr.Header().Set("Proxy-Authenticate", `Basic realm="dumbproxy"`)
-		wr.Header().Set("Content-Length", strconv.Itoa(len([]byte(AUTH_REQUIRED_MSG))))
-		wr.WriteHeader(407)
-		wr.Write([]byte(AUTH_REQUIRED_MSG))
-	}
+
```
Comment (Snawoot) [inline auth/common.go]: I think we still need to send AUTH_REQUIRED_MSG and 407 code right before last return if neither hidden_domain is set nor next chained auth provider is set. Otherwise it'll be returning 200 and empty body to each unauthorized request.

E.g. I run this code like this:

```
go run . -auth 'static://?username=admin&password=123456'
```

and test it with curl:

```
user@ws:~> curl -D- -x 0:8080 2ip.ru
HTTP/1.1 200 OK
Date: Sun, 22 Mar 2026 12:15:33 GMT
Content-Length: 0

user@ws:~> curl -D- -x 0:8080 https://2ip.ru
HTTP/1.1 200 OK
Date: Sun, 22 Mar 2026 12:15:38 GMT
Content-Length: 0

curl: (35) TLS connect error: error:0A00010B:SSL routines::wrong version number
```

**Review by Snawoot — CHANGES_REQUESTED** [review]

**Comment by Snawoot** [comment]
Thank you for the contribution! I've requested changes to handle "the usual" case work properly. It would be nice to handle 407 rejection in a common branch or at least in a common routine.

**Comment by sanekb** [comment]
Actually, I didn't intend to change the behavior so radically; I overlooked the code — my mistake!

Could we rely on the standard Error function, similar to how BAD_REQ_MSG is handled, so it sets the Content-Length automatically and makes the code a bit cleaner?

**Review by Snawoot — APPROVED** [review]

**Comment by Snawoot** [comment]
Yeah, it's much better. http server will buffer a first portion of response and calculate header properly anyway, so this is cleaner indeed. I'll apply couple more fixes to issues I spotted in other places, merge and release it soon.

Thank you!
